spring:
  application:
    name: file-upload
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 200MB
      max-request-size: 215MB
  kafka:
    consumer:
      enable-auto-commit: false
      auto-offset-reset: "earliest"
      group-id: "hright1"

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  profiles: local
  kafka:
    consumer:
      bootstrap-servers: http://localhost:9092
    producer:
      bootstrap-servers: http://localhost:9092

dm:
  aws:
    enabled: false

file:
  storage:
    location: /tmp

kafka:
  topic:
    file-processor: "FILE_PROCESSOR_TOPIC"
    elastic-search: "ELASTIC_SEARCH_TOPC"
