spring:
  application:
    name: file-upload
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 200MB
      max-request-size: 215MB

---
spring:
  profiles: local

dm:
  aws:
    enabled: false

file:
  storage:
    location: /tmp

