server:
  port: 8081
spring:
  application:
    name: file-processor
  kafka:
    consumer:
      enable-auto-commit: false
      auto-offset-reset: "earliest"
      group-id: "hright1"

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

disruptor:
  buffer-size: 64
  handler:
    document-publish-handler-count: 2
    pdf-parser-handler-count: 8
    send-down-stream-handler-count: 2
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    consumer:
      bootstrap-servers: http://localhost:29092
    producer:
      bootstrap-servers: http://localhost:29092

kafka:
  topic:
    file-processor: "FILE_PROCESSOR_TOPIC"
    elastic-search: "elastic_search_topic"

tesseract:
  datapath: /usr/local/Cellar/tesseract/5.4.1/share/tessdata/

dm:
  aws:
    enabled: false

aws:
  s3:
    resume-bucket:
      bucket-name: "resume-data-bank"
      region: "ap-southeast-2"
