server:
  port: 8081
spring:
  application:
    name: file-processor
  kafka:
    consumer:
      enable-auto-commit: false
      auto-offset-reset: "earliest"
      group-id: "hright1"

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

disruptor:
  buffer-size: 64
  handler:
    document-publish-handler-count: 2
    pdf-parser-handler-count: 8
    send-down-stream-handler-count: 2
---
spring:
  profiles: local
  kafka:
    consumer:
      bootstrap-servers: http://localhost:9092
    producer:
      bootstrap-servers: http://localhost:9092

kafka:
  topic:
    file-processor: "FILE_PROCESSOR_TOPIC"
    elastic-search: "ELASTIC_SEARCH_TOPIC"

tesseract:
  datapath: /Users/athul

dm:
  aws:
    enabled: false
