spring:
  application:
    name: file-processor

---
spring:
  profiles: local

tesseract:
  datapath: /Users/athul

dm:
  aws:
    enabled: false

file:
  storage:
    location: /tmp

disruptor:
  buffer-size: 409k6
  handler:
    document-publish-handler-count: 10
    pdf-parser-handler-count: 20
    send-down-stream-handler-count: 10